$(document).ready(function() {
    $('.display').cycle({
fx: 'fade' // choose your transition type, ex: fade, scrollUp, shuffle, etc...
});
$('#aw').show();
    $("#bw").hide();
    $("#cw").hide();
    $("#dw").hide();
    $("#ew").hide();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").hide();
    $("#lw").hide();
    $("#mw").hide();
    $("#nw").hide();
    $("#ow").hide();
     $("#pw").hide();
      $("#qw").hide();
    $("#image1").mouseover(function(){
       $("#aw").fadeIn();
       $("#bw").hide();
       $("#cw").hide();
       $('#dw').hide();
       $("#ew").hide();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").hide();
    $("#lw").hide();
    $("#mw").hide();
    $("#nw").hide();
    $("#ow").hide();
     $("#pw").hide();
      $("#qw").hide();
    });
    $("#image2").mouseover(function(){
       $("#aw").hide();
       $("#bw").fadeIn();
       $("#cw").hide();
       $('#dw').hide();
       $("#ew").hide();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").hide();
    $("#lw").hide();
    $("#mw").hide();
    $("#nw").hide();
    $("#ow").hide();
     $("#pw").hide();
      $("#qw").hide();
    });
    $("#image3").mouseover(function(){
       $("#aw").hide();
       $("#bw").hide();
       $("#cw").fadeIn();
       $('#dw').hide();
       $("#ew").hide();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").hide();
    $("#lw").hide();
    $("#mw").hide();
    $("#nw").hide();
    $("#ow").hide();
     $("#pw").hide();
      $("#qw").hide();
    });
     $("#image4").mouseover(function(){
       $("#aw").hide();
       $("#bw").hide();
       $("#cw").hide();
       $('#dw').fadeIn();
       $("#ew").hide();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").hide();
    $("#lw").hide();
    $("#mw").hide();
    $("#nw").hide();
    $("#ow").hide();
     $("#pw").hide();
      $("#qw").hide();
    });
     $("#image5").mouseover(function(){
       $("#aw").hide();
       $("#bw").hide();
       $("#cw").hide();
       $('#dw').hide();
       $("#ew").fadeIn();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").hide();
    $("#lw").hide();
    $("#mw").hide();
    $("#nw").hide();
    $("#ow").hide();
     $("#pw").hide();
      $("#qw").hide();
    });
    $("#image6").mouseover(function(){
       $("#aw").hide();
       $("#bw").hide();
       $("#cw").hide();
       $('#dw').hide();
       $("#ew").hide();
    $("#fw").fadeIn();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").hide();
    $("#lw").hide();
    $("#mw").hide();
    $("#nw").hide();
    $("#ow").hide();
     $("#pw").hide();
      $("#qw").hide();
    });
    $("#image7").mouseover(function(){
       $("#aw").hide();
       $("#bw").hide();
       $("#cw").hide();
       $('#dw').hide();
       $("#ew").hide();
    $("#fw").hide();
    $("#gw").fadeIn();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").hide();
    $("#lw").hide();
    $("#mw").hide();
    $("#nw").hide();
    $("#ow").hide();
     $("#pw").hide();
      $("#qw").hide();
    });
    $("#image8").mouseover(function(){
       $("#aw").hide();
       $("#bw").hide();
       $("#cw").hide();
       $('#dw').hide();
       $("#ew").hide();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").fadeIn();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").hide();
    $("#lw").hide();
    $("#mw").hide();
    $("#nw").hide();
    $("#ow").hide();
     $("#pw").hide();
      $("#qw").hide();
    });
    $("#image9").mouseover(function(){
       $("#aw").hide();
       $("#bw").hide();
       $("#cw").hide();
       $('#dw').hide();
       $("#ew").hide();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").fadeIn();
    $("#jw").hide();
    $("#kw").hide();
    $("#lw").hide();
    $("#mw").hide();
    $("#nw").hide();
    $("#ow").hide();
     $("#pw").hide();
      $("#qw").hide();
    });
    $("#image10").mouseover(function(){
       $("#aw").hide();
       $("#bw").hide();
       $("#cw").hide();
       $('#dw').hide();
       $("#ew").hide();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").fadeIn();
    $("#kw").hide();
    $("#lw").hide();
    $("#mw").hide();
    $("#nw").hide();
    $("#ow").hide();
     $("#pw").hide();
      $("#qw").hide();
    });
    $("#image11").mouseover(function(){
       $("#aw").hide();
       $("#bw").hide();
       $("#cw").hide();
       $('#dw').hide();
       $("#ew").hide();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").fadeIn();
    $("#lw").hide();
    $("#mw").hide();
    $("#nw").hide();
    $("#ow").hide();
     $("#pw").hide();
      $("#qw").hide();
    });
    $("#image12").mouseover(function(){
       $("#aw").hide();
       $("#bw").hide();
       $("#cw").hide();
       $('#dw').hide();
       $("#ew").hide();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").hide();
    $("#lw").fadeIn();
    $("#mw").hide();
    $("#nw").hide();
    $("#ow").hide();
     $("#pw").hide();
      $("#qw").hide();
    });
    $("#image13").mouseover(function(){
       $("#aw").hide();
       $("#bw").hide();
       $("#cw").hide();
       $('#dw').hide();
       $("#ew").hide();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").hide();
    $("#lw").hide();
    $("#mw").fadeIn();
    $("#nw").hide();
    $("#ow").hide();
     $("#pw").hide();
      $("#qw").hide();
    });
    $("#image14").mouseover(function(){
       $("#aw").hide();
       $("#bw").hide();
       $("#cw").hide();
       $('#dw').hide();
       $("#ew").hide();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").hide();
    $("#lw").hide();
    $("#mw").hide();
    $("#nw").fadeIn();
    $("#ow").hide();
     $("#pw").hide();
      $("#qw").hide();
    });
    $("#image15").mouseover(function(){
       $("#aw").hide();
       $("#bw").hide();
       $("#cw").hide();
       $('#dw').hide();
       $("#ew").hide();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").hide();
    $("#lw").hide();
    $("#mw").hide();
    $("#nw").hide();
    $("#ow").fadeIn();
     $("#pw").hide();
      $("#qw").hide();
    });
    $("#image16").mouseover(function(){
       $("#aw").hide();
       $("#bw").hide();
       $("#cw").hide();
       $('#dw').hide();
       $("#ew").hide();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").hide();
    $("#lw").hide();
    $("#mw").hide();
    $("#nw").hide();
    $("#ow").hide();
     $("#pw").fadeIn();
      $("#qw").hide();
    });
    
    
    $("#image1,#image2,#image3,#image4,#image5,#image6,#image7,#image8,#image9,#image10,#image11,,#image12,#image13,#image14,#image15,#image16").mouseleave(function(){
       $("#aw").hide();
       $("#bw").hide();
       $("#cw").hide();
       $('#dw').fadeIn();
       $("#ew").hide();
    $("#fw").hide();
    $("#gw").hide();
    $("#hw").hide();
    $("#iw").hide();
    $("#jw").hide();
    $("#kw").hide();
    });


    //sign in hide show
    $("#as").mouseover(function() {
        $(".menuListOne").hide();
        $(".menuListTwo").hide();
        $(".menuList").show();
    });
    $("#bs").mouseenter(function() {
        $(".menuList").hide();
        $(".menuListTwo").hide();
        $(".menuListOne").show();
        
    });
    $("#cs").mouseenter(function() {
        $(".menuList").hide();
        $(".menuListOne").hide();
        $(".menuListTwo").show();
        
    });
    
    $("#ds").mouseenter(function() {
        $(".menuList").show();
        
        
    });
    $("#es").mouseenter(function() {
        $(".menuListOne").show();
        
        
    });
    $(".item,.menuList,.menuListOne").mouseleave(function(){
$(".menuList").hide();
        $(".menuListOne").hide();
        $(".menuListTwo").hide();
        
    });
    
    
});
